# Generated by Django 5.0.3 on 2024-04-11 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_pontofuncao'),
        ('user', '0010_alter_user_imagem_delete_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('dat_insercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('dat_delete', models.DateTimeField(blank=True, null=True)),
                ('usr_insercao', models.IntegerField(blank=True, null=True)),
                ('usr_edicao', models.IntegerField(blank=True, null=True)),
                ('usr_delete', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nm_descritivo', models.CharField(max_length=500, null=True)),
                ('is_cadastro_regional', models.BooleanField(default=False)),
                ('cargo_pai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_cargopai', to='funcionario.cargo')),
            ],
            options={
                'db_table': 'funcionario_cargo',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('dat_insercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('dat_delete', models.DateTimeField(blank=True, null=True)),
                ('usr_insercao', models.IntegerField(blank=True, null=True)),
                ('usr_edicao', models.IntegerField(blank=True, null=True)),
                ('usr_delete', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('celular_numero', models.CharField(max_length=50, null=True)),
                ('celular_ddd', models.CharField(max_length=3, null=True)),
                ('celular_completo', models.CharField(max_length=50, null=True)),
                ('celular_completo_form', models.CharField(max_length=50, null=True)),
                ('telefone_numero', models.CharField(max_length=50, null=True)),
                ('telefone_ddd', models.CharField(max_length=3, null=True)),
                ('telefone_completo', models.CharField(max_length=50, null=True)),
                ('telefone_completo_form', models.CharField(max_length=50, null=True)),
                ('email_financeiro', models.EmailField(max_length=200, null=True)),
                ('email_documentacao', models.EmailField(max_length=200, null=True)),
                ('nm_completo', models.CharField(max_length=200, null=True)),
                ('nm_primeiro', models.CharField(max_length=200, null=True)),
                ('nm_ultimo', models.CharField(max_length=200, null=True)),
                ('nm_social_completo', models.CharField(max_length=200, null=True)),
                ('nm_social_primeiro', models.CharField(max_length=200, null=True)),
                ('nm_social_ultimo', models.CharField(max_length=200, null=True)),
                ('nm_documento_completo', models.CharField(max_length=200, null=True)),
                ('nm_documento_primeiro', models.CharField(max_length=200, null=True)),
                ('nm_documento_ultimo', models.CharField(max_length=200, null=True)),
                ('cpf', models.BigIntegerField(null=True)),
                ('cpf_form', models.CharField(max_length=20, null=True)),
                ('rg', models.CharField(max_length=15, null=True)),
                ('rg_form', models.CharField(max_length=15, null=True)),
                ('passaporte', models.CharField(max_length=200, null=True)),
                ('passaporte_form', models.CharField(max_length=200, null=True)),
                ('dat_nasc', models.DateField(null=True)),
                ('imagem', models.TextField(default='fotos/sem-foto.png', null=True)),
                ('nm_mae', models.CharField(max_length=200, null=True)),
                ('nm_pai', models.CharField(max_length=200, null=True)),
                ('dat_admissao', models.DateTimeField(null=True)),
                ('matricula', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('is_adm', models.BooleanField(default=False, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('numero_cadastro_regional', models.CharField(max_length=200, null=True)),
                ('tipo_cadastro_regional', models.CharField(max_length=200, null=True)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.cargo')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_endereco', to='core.endereco')),
                ('funcionario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_funcionarioresponsavel', to='funcionario.funcionario')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
    ]
