# Generated by Django 5.0.3 on 2024-04-11 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pontofuncao'),
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('dat_insercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('dat_delete', models.DateTimeField(blank=True, null=True)),
                ('usr_insercao', models.IntegerField(blank=True, null=True)),
                ('usr_edicao', models.IntegerField(blank=True, null=True)),
                ('usr_delete', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('nivel', models.IntegerField(null=True)),
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nm_descritivo', models.CharField(max_length=200, null=True)),
                ('descricao', models.CharField(max_length=500, null=True)),
                ('tela_principal_referencia', models.CharField(max_length=128, null=True)),
                ('grupo_pai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_grupo_pai', to='funcionario.grupo')),
            ],
            options={
                'db_table': 'funcionario_grupo',
            },
        ),
        migrations.CreateModel(
            name='GrupoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_insercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('dat_delete', models.DateTimeField(blank=True, null=True)),
                ('usr_insercao', models.IntegerField(blank=True, null=True)),
                ('usr_edicao', models.IntegerField(blank=True, null=True)),
                ('usr_delete', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('codigo', models.IntegerField(help_text='Código da área que o grupo faz parte', null=True)),
                ('cd_tipo_area', models.CharField(help_text='Código do tipo da área que o grupo faz parte', max_length=200, null=True)),
                ('tipo', models.CharField(max_length=200, null=True)),
                ('tela_principal', models.CharField(max_length=128, null=True)),
                ('ordem', models.IntegerField(null=True)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.funcionario')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.grupo')),
            ],
            options={
                'db_table': 'funcionario_grupofuncionario',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_insercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('dat_delete', models.DateTimeField(blank=True, null=True)),
                ('usr_insercao', models.IntegerField(blank=True, null=True)),
                ('usr_edicao', models.IntegerField(blank=True, null=True)),
                ('usr_delete', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('nome', models.CharField(max_length=256, null=True)),
                ('descricao', models.CharField(max_length=512, null=True)),
                ('modulo', models.CharField(max_length=128, null=True)),
                ('perfil_pai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.perfil')),
            ],
            options={
                'db_table': 'funcionario_perfil',
            },
        ),
        migrations.CreateModel(
            name='PerfilPontoFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_insercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('dat_delete', models.DateTimeField(blank=True, null=True)),
                ('usr_insercao', models.IntegerField(blank=True, null=True)),
                ('usr_edicao', models.IntegerField(blank=True, null=True)),
                ('usr_delete', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.perfil')),
                ('ponto_funcao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.pontofuncao')),
            ],
            options={
                'db_table': 'funcionario_perfilpontofuncao',
            },
        ),
        migrations.CreateModel(
            name='PerfilUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_insercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('dat_delete', models.DateTimeField(blank=True, null=True)),
                ('usr_insercao', models.IntegerField(blank=True, null=True)),
                ('usr_edicao', models.IntegerField(blank=True, null=True)),
                ('usr_delete', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.funcionario')),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.perfil')),
            ],
            options={
                'db_table': 'funcionario_perfilfuncionario',
            },
        ),
        migrations.CreateModel(
            name='PontoFuncaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_insercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('dat_delete', models.DateTimeField(blank=True, null=True)),
                ('usr_insercao', models.IntegerField(blank=True, null=True)),
                ('usr_edicao', models.IntegerField(blank=True, null=True)),
                ('usr_delete', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.funcionario')),
                ('ponto_funcao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.pontofuncao')),
            ],
            options={
                'db_table': 'funcionario_pontofuncaofuncionario',
            },
        ),
    ]
