# Generated by Django 5.0.3 on 2024-04-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estado_tipo_endereco'),
        ('user', '0007_remove_perfilpontofuncao_ponto_funcao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PontoFuncao',
        ),
    ]
