# Generated by Django 5.0.3 on 2024-04-11 15:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agenda_funcionario_agenda_funcionario_marcacao_and_more'),
        ('cliente', '0002_rename_usuario_user_user'),
        ('core', '0005_pontofuncao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Cliente',
        ),
    ]
