# Generated by Django 5.0.3 on 2024-04-11 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('cliente', '0002_rename_usuario_user_user'),
        ('funcionario', '0003_alter_funcionario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_funcionario', to='funcionario.funcionario'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='funcionario_marcacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario_marcacao', to='funcionario.funcionario'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='paciente_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente'),
        ),
    ]
