# Generated by Django 5.0.3 on 2024-04-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agenda_funcionario_agenda_funcionario_marcacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='funcionario_marcacao',
        ),
    ]
