# Generated by Django 5.0.3 on 2024-04-11 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_agenda_funcionario_and_more'),
        ('cliente', '0003_rename_user_cliente'),
        ('funcionario', '0003_alter_funcionario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agenda_funcionario', to='funcionario.funcionario'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='funcionario_agendamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funcionario_agendamento', to='funcionario.funcionario'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='paciente_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente'),
        ),
    ]
