# Generated by Django 5.0.3 on 2024-04-15 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agenda_funcionario_agenda_funcionario_agendamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='paciente_id',
            new_name='paciente',
        ),
    ]
