# Generated by Django 5.0.3 on 2024-04-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_rename_paciente_id_agenda_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='descricao',
            new_name='observacao',
        ),
        migrations.AddField(
            model_name='agenda',
            name='procedimento',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
