# Generated by Django 5.0.3 on 2024-04-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_rename_paciente_agenda_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='is_concluido',
            field=models.BooleanField(null=True),
        ),
    ]
