# Generated by Django 5.0.3 on 2024-04-11 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_pontofuncao'),
        ('filial', '0001_initial'),
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_funcionarioresponsavel', to='funcionario.funcionario'),
        ),
        migrations.AddField(
            model_name='filial',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_area', to='filial.area'),
        ),
        migrations.AddField(
            model_name='filial',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_endereco', to='core.endereco'),
        ),
        migrations.AddField(
            model_name='filial',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_funcionarioresponsavel', to='funcionario.funcionario'),
        ),
    ]
