# Generated by Django 5.0.3 on 2024-04-01 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_grupouser_usuario_perfiluser_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiluser',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='grupouser',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
