# Generated by Django 5.0.3 on 2024-04-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_grupouser_usuario_perfiluser_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupouser',
            name='dat_fim',
        ),
        migrations.RemoveField(
            model_name='grupouser',
            name='dat_ini',
        ),
        migrations.RemoveField(
            model_name='grupouser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='grupo',
            name='tela_principal_referencia',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='grupouser',
            name='tela_principal',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
