# Generated by Django 5.0.3 on 2024-04-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_grupouser_dat_fim_remove_grupouser_dat_ini_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilpontofuncao',
            name='ponto_funcao',
        ),
    ]
