# Generated by Django 5.0.3 on 2024-04-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_perfilpontofuncao_ponto_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupouser',
            name='ordem',
            field=models.IntegerField(null=True),
        ),
    ]
