# Generated by Django 5.0.3 on 2024-04-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_grupouser_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagem',
            field=models.TextField(default='fotos/sem-foto.png', null=True),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
