# Generated by Django 5.0.3 on 2024-04-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_imagem_delete_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupouser',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='grupouser',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='perfil_pai',
        ),
        migrations.RemoveField(
            model_name='perfiluser',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='perfilpontofuncao',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='perfilpontofuncao',
            name='ponto_funcao',
        ),
        migrations.RemoveField(
            model_name='perfiluser',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='GrupoUser',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='PerfilPontoFuncao',
        ),
        migrations.DeleteModel(
            name='PerfilUser',
        ),
    ]
